# permissions for end users to view podtrackers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: podtracker-viewer-role
rules:
- apiGroups:
  - crd.devops.toolbox
  resources:
  - podtrackers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - crd.devops.toolbox
  resources:
  - podtrackers/status
  verbs:
  - get
